 name: CI Workflow
 on: [push, pull_request]
 jobs:
  build:
    runs-on: ubuntu-latest
     steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Dependencies
      - name: KT NPM
        uses: kloudtek/kt-gh-action-npm@0.8.2
        run: npm install
      - name: Run Tests
        run: npm test
